name: Vote Workflow

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'vote/**'
      - '.github/workflows/vote-workflow.yml'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'vote/**'
      - '.github/workflows/vote-workflow.yml'
  schedule:
    # re-run montly to keep image fesh with upstream base images
    - cron: '0 12 15 * *'

jobs:
  build-image:
    name: Build Vote Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
   
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: "{{defaultContext}}:vote"
          tags: gabrielmsollero/example-voting-app_vote:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max